name: pylibseq_docs

channels:
    - conda-forge
    - defaults
    - r
    - bioconda

dependencies:
    - sphinx_rtd_theme==0.1.9
    - pybind11==2.2.2
    - libsequence
    - ipython
    - matplotlib
