name: pylibseq_docs

channels:
    - conda-forge
    - defaults
    - r
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme==0.1.9
    - pybind11==2.2.1
    - libsequence
    - ipython
