name: pylibseq_docs

channels:
    - conda-forge
    - defaults
    - r
    - bioconda

dependencies:
    - python==3.5
    - sphinx_rtd_theme==0.1.9
    - libsequence
    - ipython
    - matplotlib
    - pandas
    - msprime
    - gsl
    - hdf5
